#!/usr/bin/python

import sys
import os
import time
from datetime import datetime
import requests
import redis
from os import path

r1 = redis.StrictRedis(host='localhost', port=6379, db=1)
r2 = redis.StrictRedis(host='localhost', port=6379, db=2)
r3 = redis.StrictRedis(host='localhost', port=6379, db=3)
r4 = redis.StrictRedis(host='localhost', port=6379, db=4)

arguments = sys.argv
arg_count = len(sys.argv)

#print (sys.argv[0])
#print (arg_count)
#exit()


if len(sys.argv) == 2:
    function = sys.argv[1] 


def runtime():

    # Check and confirm that exactly and only one function is passed at a time as argument to this script
    if arg_count == 2:

        if path.exists(function):

            ext = arguments[1].split('.')

            if len(ext) > 1:
                runtime = ext[1]

                if runtime == 'py':
                    print("\nRuntime is python!")
                    return ("python")
                elif runtime == 'js':
                    print("\nRuntime is JavaScript!")
                    return ("nodejs")
                elif runtime == 'rb':
                    print("\nRuntime is Ruby!")
                    return ("ruby")
                elif runtime == 'jar':
                    print("\nRuntime is Java!")
                    return ("java")
                elif runtime == 'php':
                    print("\nRuntime is PHP!")
                    return ("php")
                elif runtime == 'swift':
                    print("\nRuntime is Swift!")
                    return ("swift")
                elif runtime == 'go':
                    print("\nRuntime is Go!")
                    return ("go")
                else:
                    print("\nUnknown runtime! Quitting!")
                    exit()

            else:
                print("Runtime could not be identified! Quitting!")
                exit()

        else:
            print ("\nThe specified function - {} could not be found!\n".format(function))
            print ("Please check the input again!\n")
            print ("Quitting the execution now!\n")
            time.sleep(1)
            exit()

    elif arg_count > 2:
        print ("\nThere are more than one functions found! Please enter only one at a time!\n")
        print ("Quitting the execution now!\n")
        time.sleep(1)
        exit()

    elif arg_count == 1:
        print("\nNo function found to execute! Quitting!\n")
        print("Quitting the execution now!\n")
        time.sleep(1)
        exit()



def container_pulse(container):

    cmd = "ps -ef | grep %s | grep docker | wc -l"%(container)
    count =  os.popen(cmd).read().strip()

    if int(count) > 1:
        pulse  = 1          #Pulse = 1 means warm container is already occupied
    else:
        pulse = 0           #Pulse = 0 means warm container is free and not occupied

    return (pulse)


def libraries(container):
    
    
    cmd = "cat %s | grep ^import | sed -e 's/import//g' | sed 's/ //g'" % (function)
    cont = os.popen(cmd).read().strip()
    lib = cont.split()
    
    #print(lib)
    
    for x in lib:
    
        response = requests.get("https://pypi.org/pypi/{}/json".format(x))
    
        if response.status_code == 200:  # Checks if the library is valid
    
            #call cache.py here and install libraries in the new container
    
            lib_cpath = x + '_cpath'
    
            if r3.exists(lib_cpath) == True:
                ## Use the path, install and call cache.py
    
                whl_path = r3.get(lib_cpath)
    
                splt_char = "/"
                K = 3
    
                temp = whl_path.split(splt_char)
                res = splt_char.join(temp[:K]), splt_char.join(temp[K:])
    
                whl = '/cache/' + res[1]

                cmd1 = 'echo $(($(date +%s%N)/1000000))'
                exec_start = os.popen(cmd1).read().strip()
    
                cmd2 = "docker exec -i {0} pip install {1} && echo $(($(date +%s%N)/1000000)) > /tmp/pip_log".format(container,whl)
                os.system(cmd2)
                
                cmd3 = ("cat /tmp/pip_log")
                exec_end = os.popen(cmd3).read().strip()

                install_time = (int(exec_end)-int(exec_start))

                cache(x, install_time)
    
            else:
                
                #Dowload, install and call the cache.py

                print("Downloading libraries as it's not found in cache")

                cmd1 = 'echo $(($(date +%s%N)/1000000))'
                exec_start = os.popen(cmd1).read().strip()

                cmd2 = "docker exec -i {0} pip install {1} && echo $(($(date +%s%N)/1000000)) > /tmp/pip_log".format(container,x)
                os.system(cmd2)

                cmd3 = ("cat /tmp/pip_log")
                exec_end = os.popen(cmd3).read().strip()

                install_time = (int(exec_end)-int(exec_start))

                cache(x, install_time)



def resource(env):
    
    
    #cmd = "docker ps | grep -i %s | grep -i warm | grep -v prewarm | wc -l"%(env)
    cmd = 'docker ps --filter "name=warm0_" | grep %s | wc -l'%(env)
    cont = os.popen(cmd).read().strip()
    print ("\nNo. of warm {} containers running - {}\n".format(env,cont))


    cmd1 = "docker ps | grep -i %s | grep -i warm | grep -v prewarm | wc -l"%(env)
    warm = os.popen(cmd1).read().strip()


    if warm == 1:   #This means at least one warm container is present

        cmd = "docker ps --format '{{.Names}}' | grep -i %s | grep -i warm | grep -v prewarm"%(env)
        out = os.popen(cmd).read().strip().split()
        containers = sorted(out)

        for x in containers:

            pulse = container_pulse(x)

            if pulse == 0:
                container = x
                break

        ##install libraries
        libraries(container)
        execute(container,function)

    else:        #Create a new warm container and install libraries from Cache


        cmd1 = "docker run -v /root/.cache/:/cache/ -dit --name warm0_12_python2 python:2.7-alpine"
        os.popen(cmd1)

        libraries("warm0_12_python2")
        execute("warm0_12_python2", function)


    
def execute(container,request): #to execute the function and then stop the container


    cmd0 = "docker cp {0} {1}:/".format(request, container)
    os.popen(cmd0)

    print "\n\n"

    cmd1 = "docker exec -i {0} python /{1}".format(container,request)
    os.system(cmd1)

    print "\nExecution complete!\n"

    cmd2 = "docker container kill {0}".format(container)
    os.popen(cmd2)

    cmd3 = "docker container rm {0}".format(container)
    os.popen(cmd3)


def cache(lib, time):

    lib_freq = lib+'_freq'
    lib_count = lib+'_count'
    lib_cpath = lib+'_cpath'
    lib_last_used = lib+'_last_used'
    lib_install_time = 'time'
    cpath = 'None'

    cache_dir = "/root/.cache/pip/wheels"

    now = datetime.now()
    today = now.strftime("%Y-%m-%d")

    if path.exists(cache_dir):

        cmd = "find %s -name '*.whl' | grep -i %s"%(cache_dir,lib)
        cpath = os.popen(cmd).read().strip()


    entry = r1.exists(lib_freq)
    freq = r1.get(lib_freq)
    #print(r1.get(lib_freq))
    #print(freq)


    if entry == 0:
        r1.set(lib_freq,'NEW')
        r2.set(lib_count,1)
        r4.set(lib_last_used,today)


    elif (entry !=0 and freq == 'NEW'):
        r1.set(lib_freq,'INFREQUENT')
        r2.set(lib_count,2)
        r4.set(lib_last_used,today)
    elif (entry !=0 and freq == 'INFREQUENT'):

        count = int(r2.get(lib_count))

        if count >= 5:

            r1.set(lib_freq,'FREQUENT')
            r4.set(lib_last_used,today)

            # Find the cache path, update it in redis and retain the cache

            cmd = "find ~/.cache/pip/wheels -name '*.whl' |grep -i %s-"%lib
            result = os.popen(cmd).read().strip()
            cpath = result.split()

            if path.exists(cpath[0]):
                r3.set(lib_cpath,cpath[0])

        elif count < 5:

            count += 1
            r2.set(lib_count,count)
            r4.set(lib_last_used,today)


    elif (entry !=0 and freq == 'FREQUENT'):

        # Check last used date of library, if it's used more than 10 days before then delete it and set status again to infrequent
        # print("The library is used frequently!")
        r4.set(lib_last_used,today)

    now = datetime.now()
    today = now.strftime("%Y-%m-%d")
    last_used = r4.get(lib_last_used)

    d1 = datetime.strptime(today, "%Y-%m-%d")
    d2 = datetime.strptime(last_used, "%Y-%m-%d")
    difference = (abs((d1 - d2).days))

    if difference == 0:

        ##remove the cache
        #print ("Library was used very recently!")

        r1.exists(lib_cpath)
        #print (path)


env = runtime()
pulse = resource(env)
